const EXPECTED_CANVASKIT_UNSUPPORTED_OPS = new Set([
  'charOverlap',
  'equation:invalidLayoutFallback',
  'equation:unsupportedDirectReplay',
  'glyphOutline',
  'glyphOutline:glyphOutlineStrokeStyleUnsupported',
  'glyphOutline:unsupportedBitmapGlyph',
  'glyphOutline:unsupportedColorGlyph',
  'glyphOutline:unsupportedOutlinePayload',
  'glyphOutline:unsupportedSvgGlyph',
  'glyphRun',
  'image:dataMissing',
  'image:dimensionUnavailable',
  'image:invalidBounds',
  'image:tileLimit',
  'imageEffect:blackWhite',
  'imageEffect:brightnessContrast',
  'imageEffect:grayScale',
  'imageEffect:pattern8x8',
  'rawSvg:unsupportedDirectReplay',
  'tabLeader',
  'textControlMark',
  'textDecoration',
  'textRun:embossTextEffect',
  'textRun:emphasisDot',
  'textRun:engraveTextEffect',
  'textRun:glyphMapping',
  'textRun:layoutPositions',
  'textRun:outlineTextEffect',
  'textRun:ratioTextEffect',
  'textRun:scriptTextRequiresShaping',
  'textRun:shadeTextEffect',
  'textRun:shadowTextEffect',
  'textRun:textDecoration',
  'textRun:verticalText',
  'textRunFont',
]);

export function isExpectedCanvasKitUnsupportedOp(op: string): boolean {
  return EXPECTED_CANVASKIT_UNSUPPORTED_OPS.has(op);
}
